language: node_js
node_js:
  - "10"

before_script: npm run build
script: sh live.sh
deploy:
  local-dir: live
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
